name: Server Pipeline

on:
  push:
    branches: 
      - main
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub 
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t lukaneek/demo:latest .
    - name: Push to Dockerhub
      run: docker push lukaneek/demo:latest

  deploy:
    needs: build
    runs-on: self-hosted 
  
    steps:
    - name: Pull docker image
      run: sudo docker pull lukaneek/demo:latest
    - name: Delete old docker container
      run: sudo docker rm -f demo || true
    - name: Run docker container
      run: sudo docker run -d -p 8080:8080 --name demo lukaneek/demo
